version: '2'
services:
  diploma-app:
    image: diploma
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://diploma-postgresql:5432/Diploma
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  diploma-postgresql:
    extends:
      file: postgresql.yml
      service: diploma-postgresql
